apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-rancher
spec:
  selector:
    matchLabels:
      app: nginx
      tier: test
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        tier: test
    spec:
      containers:
      - name: nginx
        image: suleiman/nginx:3.2.1 # {"$imagescan": "test-scan"}
        ports:
        - containerPort: 80
